const pptxgen = require('pptxgenjs');
const { imageSizingCrop, warnIfSlideHasOverlaps, warnIfSlideElementsOutOfBounds } = require('/home/oai/skills/slides/pptxgenjs_helpers');
const pptx = new pptxgen();
pptx.layout = 'LAYOUT_WIDE'; pptx.author = 'ULPF SIH Team'; pptx.subject = 'Universal Log Pre-processing Framework'; pptx.title = 'ULPF Technical Pitch';
pptx.theme = { headFontFace: 'Aptos Display', bodyFontFace: 'Aptos', lang: 'en-US' };
const W=13.333,H=7.5; const c={bg:'07111F',panel:'0D1D33',panel2:'102744',blue:'68A7FF',cyan:'65E3FF',green:'9CFCCB',text:'EAF2FF',muted:'AFC2E2',line:'2B5689',pink:'FFB4C3',orange:'FFD27D'};
function bg(s){s.background={color:c.bg};s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:W,h:H,fill:{color:c.bg},line:{color:c.bg,transparency:100}})}
function title(s,t,sub){s.addText(t,{x:.55,y:.38,w:8.5,h:.52,fontSize:31,bold:true,color:c.text,margin:0}); if(sub)s.addText(sub,{x:.58,y:.93,w:9.5,h:.26,fontSize:12,color:c.muted,margin:0}); s.addText('ULPF · SIH26156',{x:10.62,y:.43,w:2.15,h:.28,fontSize:10,bold:true,color:c.blue,margin:0,align:'right'})}
function footer(s,txt='One schema · Any supported perimeter device · Zero forensic data loss'){s.addText(txt,{x:.58,y:7.08,w:8.4,h:.25,fontSize:9.5,color:c.muted,margin:0})}
function pill(s,text,x,y,w,color=c.panel2){s.addText(text,{x,y,w,h:.35,fontSize:10.5,bold:true,color:c.text,align:'center',valign:'mid',margin:.04,shape:pptx.ShapeType.roundRect,fill:{color},line:{color:c.line,width:1}})}
function stat(s,big,label,x,y,w=1.62){s.addText([{text:big,options:{bold:true,fontSize:24,color:c.text}},{text:'\n'+label,options:{fontSize:8.5,color:c.muted}}],{x,y,w,h:.9,margin:.06,valign:'mid',shape:pptx.ShapeType.roundRect,fill:{color:c.panel},line:{color:c.line,width:.9},fit:'shrink'})}
function callout(s,text,x,y,w,accent=c.cyan){s.addText(text,{x,y,w,h:.56,fontSize:12.5,bold:true,color:c.text,valign:'mid',margin:.08,shape:pptx.ShapeType.roundRect,fill:{color:c.panel},line:{color:accent,width:1.2},fit:'shrink'})}
function check(s){warnIfSlideHasOverlaps(s,pptx,{ignoreLines:true,ignoreDecorativeShapes:true}); warnIfSlideElementsOutOfBounds(s,pptx)}
{
const s=pptx.addSlide(); bg(s); s.addText('Universal Log\nPre-processing\nFramework',{x:.66,y:.74,w:5.7,h:1.95,fontSize:40,bold:true,color:c.text,fit:'shrink',margin:0}); s.addText('One schema. Any supported perimeter device. Zero forensic data loss.',{x:.72,y:3,w:5.7,h:.34,fontSize:16,color:c.blue,margin:0}); s.addText('Problem: every firewall/device speaks a different log language. Teams burn time before security analytics can even begin.',{x:.74,y:3.72,w:5.2,h:.7,fontSize:15,color:c.muted,fit:'shrink',margin:0}); pill(s,'FortiGate',6.6,1.05,1.4);pill(s,'Cisco ASA',8.17,1.05,1.4);pill(s,'PAN-OS',9.74,1.05,1.3);pill(s,'CEF',11.18,1.05,.82);pill(s,'Syslog',12.13,1.05,.86); s.addText('five vendor formats  →',{x:7,y:2.02,w:2.65,h:.3,fontSize:15,bold:true,color:c.cyan,margin:0,align:'center'}); s.addText('ULPF translation layer',{x:7.08,y:3.08,w:5.35,h:.72,fontSize:22,bold:true,color:c.text,align:'center',valign:'mid',margin:.06,shape:pptx.ShapeType.roundRect,fill:{color:c.panel},line:{color:c.cyan,width:1.5}}); s.addShape(pptx.ShapeType.line,{x:9.75,y:3.88,w:0,h:.8,line:{color:c.cyan,width:1.6,endArrowType:'triangle'}}); s.addText('Normalized cyber event\n+ exact raw evidence',{x:7.42,y:4.83,w:4.7,h:.84,fontSize:20,bold:true,color:c.green,align:'center',valign:'mid',margin:.06,shape:pptx.ShapeType.roundRect,fill:{color:'0A2E2A'},line:{color:c.green,width:1.2}}); stat(s,'5','active adapters',.78,5.56,1.25);stat(s,'34/34','tests passed',2.28,5.56,1.45);stat(s,'3×','demo rehearsals passed',4,5.56,1.58);stat(s,'0%','benchmark failures',5.86,5.56,1.42); footer(s); check(s)
}
{
const s=pptx.addSlide(); bg(s); title(s,'Architecture: deterministic core, plugin edge','Known sources stay offline and deterministic; authoring assistance stays outside the hot path.'); const nodes=[['Ingest','paste · file · batch'],['Raw store','exact payload + hash'],['Detect','confidence + evidence'],['Registry','versioned plugins'],['Parse','source-shaped fields'],['Normalize','schema + taxonomy'],['Validate','safe/quarantine'],['Export','JSON · NDJSON']]; const sx=.62,y=2.05,g=.12,nw=1.42; for(let i=0;i<nodes.length-1;i++)s.addShape(pptx.ShapeType.line,{x:sx+nw+i*(nw+g),y:y+.36,w:g,h:0,line:{color:c.cyan,width:1.15,endArrowType:'triangle'}}); nodes.forEach(([n,sub],i)=>s.addText([{text:n,options:{bold:true}},{text:'\n'+sub,options:{fontSize:7.8,color:c.muted}}],{x:sx+i*(nw+g),y,w:nw,h:.75,fontSize:12,color:c.text,align:'center',valign:'mid',margin:.04,fit:'shrink',shape:pptx.ShapeType.roundRect,fill:{color:c.panel},line:{color:c.line,width:1}})); s.addText('Losslessness layer',{x:1.3,y:3.58,w:2.1,h:.33,fontSize:16,bold:true,color:c.green,margin:0}); s.addShape(pptx.ShapeType.line,{x:3.48,y:3.75,w:7.6,h:0,line:{color:c.green,width:1.5}}); s.addText('Raw payload retained · normalized event references raw ID · field trace records source field and transform · unknown events quarantined',{x:1.28,y:4.05,w:10.7,h:.45,fontSize:14,color:c.muted,margin:0,fit:'shrink'}); callout(s,'No giant vendor if/else chain',.88,5.18,2.9,c.blue); callout(s,'Independent plugin manifests + mappings',4.02,5.18,3.32,c.cyan); callout(s,'Wrong parser prevention via evidence + validation',7.58,5.18,4.08,c.green); footer(s); check(s)
}
{
const s=pptx.addSlide(); bg(s); title(s,'Live proof: one unified view across five vendors','The judge sees backend depth in the explorer and hero inspector—not a fake SOC dashboard.'); const img='/mnt/data/ulpf-final/preview/ULPF_Final_UI_Preview.png'; s.addImage({path:img,...imageSizingCrop(img,.58,1.28,8.2,5.62)}); s.addShape(pptx.ShapeType.line,{x:8.95,y:2.05,w:.7,h:-.16,line:{color:c.cyan,width:1.4,endArrowType:'triangle'}}); callout(s,'DENY filter returns 5 records across 5 source languages',9.65,1.62,2.95,c.cyan); s.addShape(pptx.ShapeType.line,{x:8.95,y:4.1,w:.68,h:.35,line:{color:c.green,width:1.4,endArrowType:'triangle'}}); callout(s,'RAW → PARSED → NORMALIZED proves traceability',9.66,4.12,2.95,c.green); stat(s,'10','judge demo events',9.66,5.68,1.38); stat(s,'5','vendors with DENY',11.18,5.68,1.38); footer(s); check(s)
}
{
const s=pptx.addSlide(); bg(s); title(s,'Innovation without weakening the deterministic path','AI/rule-based assistance helps author parsers; known-source parsing remains deterministic and offline.'); const steps=[['Unknown samples','retained + analyzed'],['Structure inference','fields + evidence'],['Mapping preview','validation warnings'],['Plugin draft','human review only'],['Activate later','fixtures must pass']]; const y=1.75,sx=.72,nw=2.1,g=.2; for(let i=0;i<steps.length-1;i++)s.addShape(pptx.ShapeType.line,{x:sx+nw+i*(nw+g),y:y+.45,w:g,h:0,line:{color:c.cyan,width:1.15,endArrowType:'triangle'}}); steps.forEach(([a,b],i)=>s.addText([{text:a,options:{bold:true}},{text:'\n'+b,options:{fontSize:9,color:c.muted}}],{x:sx+i*(nw+g),y,w:nw,h:.9,fontSize:13,color:c.text,fit:'shrink',align:'center',valign:'mid',margin:.05,shape:pptx.ShapeType.roundRect,fill:{color:c.panel},line:{color:c.line,width:1}})); s.addText('Hardening added for judging and real deployment concerns',{x:.76,y:3.42,w:7,h:.3,fontSize:18,bold:true,color:c.text,margin:0}); const bullets=['Oversized input rejected before persistence','Plugin paths validated against traversal/symlink escape','Raw logs rendered safely as text','Audit trail for parser/draft changes','Air-gap process check and Docker/Compose packaging','NDJSON export for SIEM/data-lake integration']; s.addText(bullets.map(b=>({text:b,options:{bullet:{indent:10},hanging:3}})),{x:.9,y:3.95,w:6,h:1.55,fontSize:13.5,color:c.muted,breakLine:false,fit:'shrink'}); s.addText('Benchmark snapshot',{x:8.02,y:3.42,w:3,h:.3,fontSize:18,bold:true,color:c.text,margin:0}); stat(s,'33.39','events/sec local baseline',8.08,3.95,2.05);stat(s,'26.53ms','p50 latency',10.55,3.95,1.9);stat(s,'51.27ms','p95 latency',8.08,5.05,1.95);stat(s,'0%','failure rate',10.55,5.05,1.3); s.addText('Measured on synthetic judge-demo fixtures, single process + SQLite. Not a production scale claim.',{x:8.05,y:6.08,w:4.25,h:.42,fontSize:10.5,color:c.orange,margin:0,fit:'shrink'}); footer(s); check(s)
}
{
const s=pptx.addSlide(); bg(s); title(s,'Hackathon close: what judges should remember','ULPF is the lossless preprocessing layer before SIEMs, data lakes and analytics.'); s.addText('2-minute judge flow',{x:.74,y:1.38,w:3.2,h:.38,fontSize:20,bold:true,color:c.text,margin:0}); const demo=['Show heterogeneous raw formats','Process mixed vendor batch','Filter DENY across vendors','Inspect RAW → PARSED → NORMALIZED','Show unknown onboarding draft','Close on benchmark + offline status']; s.addText(demo.map((d,i)=>({text:`${i+1}. ${d}`,options:{breakLine:true}})),{x:.86,y:1.93,w:4.45,h:2.4,fontSize:14.2,color:c.muted,margin:0,fit:'shrink'}); s.addText('Proof points',{x:6.15,y:1.38,w:3.2,h:.38,fontSize:20,bold:true,color:c.text,margin:0}); const proofs=['34/34 automated tests','three consecutive rehearsals','5 vendors normalized into one schema','exact raw recovery from normalized event','unknown events retained + quarantined','offline deterministic core']; s.addText(proofs.map(d=>({text:d,options:{bullet:{indent:10},hanging:3}})),{x:6.28,y:1.93,w:4.65,h:2.4,fontSize:14.2,color:c.muted,margin:0,fit:'shrink'}); s.addText('Winning answer in one sentence',{x:1.02,y:5.05,w:3.1,h:.32,fontSize:18,bold:true,color:c.green,margin:0}); s.addText('“It converts logs from different perimeter devices into one common event language while preserving the exact original evidence and showing where every normalized field came from.”',{x:1.02,y:5.52,w:10.8,h:.72,fontSize:17,bold:true,color:c.text,align:'center',valign:'mid',margin:.08,shape:pptx.ShapeType.roundRect,fill:{color:c.panel},line:{color:c.green,width:1.2},fit:'shrink'}); footer(s,'Next path: queue-backed stateless workers · more adapters · ECS/OCSF mappings · OpenSearch/Kafka integrations'); check(s)
}
(async()=>{await pptx.writeFile({ fileName: '/mnt/data/ulpf-final/pitch/ULPF_SIH_Technical_Pitch.pptx' });})();
